services:
  postgres:
    image: postgres:16
    container_name: aihrly_postgres
    environment:
      POSTGRES_DB: aihrly
      POSTGRES_USER: aihrly_user
      POSTGRES_PASSWORD: aihrly_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aihrly_user -d aihrly" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aihrly_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aihrly.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
  api:
    build:
      context: .
      dockerfile: src/Aihrly.Api/Dockerfile
    container_name: aihrly_api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=aihrly;\
        Username=aihrly_user;Password=aihrly_pass"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
